# This is workflow name

name: Hello workflow

on: 
   push:
      branches:
        - main
# these are jobs inside the workflow
jobs:
    greet:
        runs-on: ubuntu-latest
    
        steps:
            - name: say hello to users
              run: echo "Hello Dosto"

            - name: say hello to username
              run: echo "Hello $USER"
